### ISSUE TITLE
Is there a way to shrinkwrap devDependencies

### ISSUE THREAD

**Issue by pdehaan** [mstuart/grunt-shrinkwrap#3]
I quickly scanned the source, but didn't see any way to send `--dev` to the `npm shrinkwrap` command.

**Comment by ISMAELMARTINEZ** [comment]
I added the fix as pdehaan sugested. 

This is specially needed for https://github.com/npm/npm/issues/4161 but could be useful for other scenarios.

**Comment by ramakrishnan** [comment]
@ISMAELMARTINEZ I see the code changes made for this issue. The current change passes `--dev` all the time.
I was expecting we could pass an extra option to the grunt to have `grunt shrinkwrap:dev` So that we can shrink the npm versions for both dev and prod need.

**Comment by ramakrishnan** [comment]
My bad, there is pull request open which addressed my above comment. When can we expect this change to be available in master.

**Comment by ISMAELMARTINEZ** [comment]
Hi @ramakrishnan , Unfortunately the owner is not communicating to anyone... 

I might create a branch and put all the changes there. I will see if I got time this week to do that.

**Comment by ISMAELMARTINEZ** [comment]
@ramakrishnan and @pdehaan , do you still need this? I am happy to publish the branch that I created as grunt-shrinkwrap-dev until @mstuart adds the fixes or provides an alternative.

**Comment by kierans** [comment]
IMO the option to shrinkwrap either dev or prod dependencies shouldn't be a CLI target. Imagine you're a new user of the tool that uses this plugin, or you're configuring a build server. It's easy to forget to type `grunt shrinkwrap:dev` instead of `grunt shrinkwrap`.  The decision whether the dependencies are to be shrinkwrapped is made by the module authors and as such should be in the Gruntfile's config.  This bit me once as a devDependency changed breaking my build so I prefer to shrinkwrap all the dependencies. This is what I've done in #6.

**Comment by mstuart** [comment]
👍
